name: CI
on: [push, pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Hi
        run: |
          echo "yesss"
